action_selector: "multinomial"
epsilon_start:  0.5
epsilon_finish: .01
epsilon_anneal_time: 50000
mask_before_softmax: False

runner: "episode"

buffer_size: 512
batch_size_run: 1
batch_size: 1

# update the target network every {} training steps
target_update_interval: 200

lr: 0.0005
critic_lr: 0.0005
td_lambda: 0.8

agent_output_type: "pi_logits"
learner: "liir_learner"

name: "liir_smac"
