# --- Defaults for 4x4 predator prey, 4 agent capture, walls ---

env: "predator_prey"
env_args:
    name : PredPrey-v0

t_max: 1000000
test_nepisode: 16 # Number of episodes to test for
test_interval: 10000
